export enum HttpStatusMessage {
  NOT_FOUND = 'NOT_FOUND',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  ALREADY_EXISTS = 'ALREADY_EXISTS',
  BAD_REQUEST = 'BAD_REQUEST',
  NOT_ACCEPTABLE = 'NOT_ACCEPTABLE',
  EXPIRED_TIME = 'EXPIRED_TIME',
  OTP_EXPIRED_TIME = 'OTP_EXPIRED_TIME',
  UNAUTHORIZED = 'UNAUTHORIZED',
  OTP_NOT_MATCHED = 'OTP_NOT_MATCHED',
  BAD_REQUEST_VALIDATOR_PAYLOAD = 'BAD_REQUEST_VALIDATOR_PAYLOAD',
  TOO_MANY_REQUESTS = 'TOO_MANY_REQUESTS',
  DESIGN_NOT_FOUND = 'DESIGN_NOT_FOUND',
}

export type HttpStatusMessageType = HttpStatusMessage | string;
